language: php

php:
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

env:
  - DB_USERNAME=travis

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
# setup application:
  - |
    ./init --env=Development
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yarcode_test;'
  - cp .env.travis .env
  - php yii_test migrate --interactive=0

script:
  - composer validate --strict
  - vendor/bin/codecept run
  - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
